# Generated by Django 2.1.2 on 2018-11-05 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_postuler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lettre_motivation', models.TextField()),
                ('attachement', models.ManyToManyField(to='api.Document')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_application', to='api.Candidate')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_application', to='api.Offre')),
            ],
        ),
        migrations.RemoveField(
            model_name='postuler',
            name='attachement',
        ),
        migrations.RemoveField(
            model_name='postuler',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='postuler',
            name='offer',
        ),
        migrations.DeleteModel(
            name='Postuler',
        ),
    ]
